site_name: pxc
nav:
    - Home: index.md
    - About: about.md
    - Syntax: commands.md
    - Usage: usage/pxc.md
extra_css:
    - assets/asciinema-player.css
extra_javascript:
    - assets/asciinema-player.js
theme: material
